global:
  scrape_interval: 15s
  evaluation_interval: 30s

  external_labels:
    monitor: codelab
    foo: bar

scrape_configs:
  - job_name: scrape-static

    honor_labels: true
    # scrape_interval is defined by the configured global (15s).
    # scrape_timeout is defined by the global default (10s).

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    scheme: http

    static_configs:
      - targets: ["localhost:9090"]
        labels:
          service: prometheus
      - targets: ["worker:9464"]
        labels:
          service: worker
      - targets: ["api:3000"]
        labels:
          service: api
      - targets: ["api:9464"]
        labels:
          service: api
